### ISSUE TITLE
With Email Alias enabled Duplicate Email a user doesn't get the rejection message

### ISSUE THREAD

**Issue by BruceBuckland** [awslabs/aws-sdk-ios-samples#104] opened 2016-08-29 17:27 UTC
If I create a user pool with email set as an alias (so I can log in with email instead of username) then obviously the User Pools API requires that emails be unique across the user pool.  

But here is the problem: - (this error occurs with **signup** and with **updateAttribute** in version 2.4.7) - when I call user.updateAttribute with a duplicate email, the confirmation code goes to the duplicate email (which may be some other person) and no error occurs - the response simply gives me an encoded b***_0@o**_*s.com delivery address and no error.  

I think this is a bug, because it makes the registration system fail to inform the user of the error.  Consider this situation:  I have a typo in my email address when updating attributes, I will never get the confirmation message, (if the typo happens to be an actual email address someone else with that address will get the code).  And if I never get the confirmation message I can't enter the code and therefore can't get the error that tells me that it is duplicate.

I should note that if I am lucky enough to have access to the email address sent with the update and I use the confirmation code to confirm the updated attribute, then the continuation routine gets an error response (saying that the email is in use).   So if I am just testing software and trying different email address, I do get to see the error.  But if I am a user with a typo for an email address, then no-go.

How it should work:
The rejection due to duplicate email address should occur when i invoke updateAttribute and not when I invoke verifyAttribute.

(I have not tested with phoneNumber alias yet.  But if this error also occurs when verifying phone numbers used as aliases, I would suggest that it should also reject at updateAttribute)

For the time being I have turned off the use of aliases, and this error does not effect me.  But I really like the aliases feature and wish you would consider fixing this.

**Comment by kushwahavinay** [comment] 2016-08-31 20:18
Thanks for the feedback. 
To clarify it was a conscious design decision to create alias in verifyAttribute instead of updateAttribute.
This ensures that only the owner of the email can set alias in his account. Due to this design, alias can act like a soft link and move across accounts based on who verified it last time. 
This also enables you to claim the alias you own if some other (malicious) user has it.
Throwing duplicate email address during updateAttribute will prevent us from moving the alias to the owner account.
If you have certain use cases where you would like to prevent this behavior, we would like to hear more about it.

**Comment by BruceBuckland** [comment] 2016-09-03 21:19
Thank you for your reply.
A use case, per your request, follows.  

If I set up the user pool for email as an alias, with no MFA, what I as application designer wants is to allow my user to create an account, and give him a rejection if it doesn't work.  I can't give him a rejection if he types a duplicate email address (in error) because the rejection only appears if he types in the confirmation code.  And the confirmation code went to the wrong address.

I understand that you are trying to cover the "update attributes" condition too.  And so perhaps you could reject the duplicate email in both locations.  But there is genuine value, and a use case that supports that value, for rejecting duplicate emails upon signup, not upon entry of the confirmation code.  And for that matter upon submission of a duplicate for update attribute, rather than upon submission of the confirmation code.  

What I cannot figure is what use case supports sending the rejection after the confirmation code is entered (the way it works currently).  In order for that to make sense, the user would have to actually have ACCESS to the incorrect and duplicate email, and he seems a very unlikely person to be entering a duplicate (because he already has a password).  But maybe that is a good place to reject it too.

As it is now, I don't think it works for the common case.  And I turned it off hoping for a fix.  I suppose if you don't fix it, I could use the fetch user by username function before every attempt to use an email address, so that I could programmatically do the rejection that the API doesn't do, but that seems like a drag, and the job of the API.

Thank you for your consideration.

**Comment by kushwahavinay** [comment] 2016-09-06 20:59
Thanks for explaining your use case, Few more clarification about your use case.
Regarding "I can't give him a rejection if he types a duplicate email address (in error) because the rejection only appears if he types in the confirmation code."

What if he types a wrong email address which is not duplicate? In this case as well he will not get to confirm his account, and will not receive any error during signup.
How does it matter to the user that email is duplicate or not, if he entered the wrong email anyway.

**Comment by BruceBuckland** [comment] 2016-09-06 21:07
@kushwahavinay yes, that is true.  If he types the wrong email he does not get a confirmation either if it is not good (that's the way it is supposed to work, and it makes sense.  The failure to receive the confirmation tells the user that he did not enter the correct email).  

And given that yes, the failure to get the duplicate email might indicate the same thing.  In which case the code that told him that it was duplicate would never get run, because the user would never type in the confirmation code.

So I agree with you, it is not a bug really (unless I come to my senses) because you are making sense.

Further, If you reject duplicate emails when the user updates attributes or signs up, you would provide (unintentionally) a way for a user to determine if any email was in use, and that would not be good. 

I apologize for raising an issue that is not a bug but a design feature, and please feel free to close this issue as resolved 

thanks for your patience.

**Comment by BruceBuckland** [comment] 2016-10-28 04:49
@kushwahavinay  I now have the use case that shows this is a real problem.  

If you implement a signup process on a device, you will find that when the user gets the "duplicate email" error, the "user" is already created.  

So the user then tries to change the email to a unique one, and does signup again, but this time the username is already in use (because the user got created with the signup).

Now I suppose the app could try to delete the user (but would it have permissions without logging in?).

SO how did is the developer (me) supposed to manage a user signup.  How do I get rid of the bad username?

It would be ever so much more useful if we could be notified of a duplicate email BEFORE we called signup,  or as an error to the signup process, so that the user would not be created until we had a unique email.

Thanks

**Comment by kushwahavinay** [comment] 2016-10-31 05:25
Currently signup API does not support it. But one workaround for is to call initiateAuth to check if alias exists or not. If it succeeds this means the alias already exists and user can be prompted about it during sign up process.

**Comment by BruceBuckland** [comment] 2016-11-06 05:19
Well that seems like the right thing, if I was dealing directly with the AWS RESTful Cognito API, but I am using the aws-sdk-ios API.  So what is the equivalent?  Should I get a user from the pool and user.getSession(emailAddressToTest, password: "password that will never work" validationData: nil) and look for the error... if it says username does not exist then I am good to go, but if it says invalid username or password, then I tell the user that he tried a duplicate email?

**Comment by BruceBuckland** [comment] 2016-11-09 21:00
@kushwahavinay 
You suggested that I do initiate auth to check, and i have done that in the SDK by doing 
- Do a get session with a big long string for a password that nobody will ever type, and use the email address as the username for signup.  Do a user.getSession using that username and password.

- Switch based upon the error you get and return an appropriate task
  - If you get NotAuthorized - construct an AWSTask in error state, for the case where the mail is already in use.
  - If you get UserNotFound - return an AWSTask that does the expected getSession with the real username password and attributes
```
                    switch rejectType {
                    case AWSCognitoIdentityProviderErrorType.NotAuthorized.rawValue:
                        
                        // If it is not authorized, then the email exists as an alias to another user
                        return AWSTask(error: NSError(domain: AWSCognitoIdentityProviderErrorDomain, code: AWSCognitoIdentityProviderErrorType.UsernameExists.rawValue, userInfo: ["message":"Email already in use by a user"]))
                        
                    case AWSCognitoIdentityProviderErrorType.UserNotFound.rawValue:

                        // If it is not found, then the email is not an alias to another user and can be used
                        return self.pool!.signUp(self.usernameField.text!, password: self.passwordField.text!, userAttributes: userAttributes, validationData: nil)
                        
                    default:
                        
                        // Other errors - we will have to see
                        NSLog("When checking if email was unique encountered unexpected error type: \(rejectType) expected NotAuthorized or UserNotFound - debug - continuing")
                        return self.pool!.signUp(self.usernameField.text!, password: self.passwordField.text!, userAttributes: userAttributes, validationData: nil)
                    }
```

also @behrooziAWS points out that I can use confirmSignUp:forceAliasCreation: to "win back" the email address or phone.  I have not tried this yet in the SDK, but it looks like a good approach too.

**Comment by niip42** [comment] 2017-07-05 08:07
Hello,

Recently have been trying to work with aws mobile hub. 
Encountered same issue with repeated sign up with same email.
After reading all comments my concern is what if someone will make a bot and sign in dozens of users for one email address? 

I believe unique email is a important step to prevent spammers.

**Comment by MattHirdler** [comment] 2017-12-20 20:47
As a work around for this, could we use the Pre-Signup trigger to identify if the email is already in use, and throw an error? it's certainly not very ideal, I will say.

**Comment by desokroshan** [comment] 2018-11-14 16:10
This is a duplicate of [sdk issue#515](https://github.com/aws-amplify/aws-sdk-ios/issues/515). Closing.

**Closed by desokroshan** 2018-11-14 16:10 UTC
Labels: Cognito, SDK Issue
