### ISSUE TITLE
aws-sdk-ios generated string to sign does not match with the signature calculated

### ISSUE THREAD

**Issue by vamcyleonardo** [awslabs/aws-sdk-ios-samples#62] opened 2016-03-15 12:23 UTC
Hi,
I am trying to predict using machine learning and getting the following error.
message=The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. 
The String-to-Sign should have been
'AWS4-HMAC-SHA256
20160315T103519Z
20160315/us-east-1/machinelearning/aws4_request
853c2137861a8b1903416500e41f1bcb32783c755b35be6515aaaeda52a2ac6c' 

However, in the request i am performing, the first part .GetMLModel  as shown below to get connected to end point url was successful and the later part .Predict  fails with the above error. I am guessing the extra '/' after POST in .Predict canonical request is the culprit here. Am i right? If yes, how do i get to fix this? Thank you.

AWS4 Canonical Request: [POST/
content-type:application/x-amz-json-1.1
host:machinelearning.us-east-1.amazonaws.com
user-agent:aws-sdk-iOS/2.3.5 iPhone-OS/9.2 en_US
x-amz-date:20160316T054451Z
x-amz-target:AmazonML_20141212.GetMLModel
content-type;host;user-agent;x-amz-date;x-amz-target
24f129cce16214ecf6584d72aa625c24390f38674c5c37eb041e9bd044b94ed1]

AWS4 Canonical Request: [POST//
content-type:application/x-amz-json-1.1
host:realtime.machinelearning.us-east-1.amazonaws.com,realtime.machinelearning.us-east-1.amazonaws.com
user-agent:aws-sdk-iOS/2.3.5 iPhone-OS/9.2 en_US
x-amz-date:20160316T054458Z
x-amz-target:AmazonML_20141212.Predict
content-type;host;user-agent;x-amz-date;x-amz-target
da2d7f28d79e55082d66964fce4882a87657975222a8dfb5fb7c0d014d274de0]

**Comment by yosuke-matsuda** [comment] 2016-03-16 21:06
Seems like a duplicate of [this issue](https://github.com/aws/aws-sdk-ios/issues/331). Merging it to this thread.

**Closed by yosuke-matsuda** 2016-03-16 21:06 UTC
